"""This is a basic playing card for the game schrööm."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['suits', 'ranks', 'Card']

# %% ../nbs/00_card.ipynb 4
suits = ['♤','♡','♢','♧']
ranks = [None, 'J','Q','K','A'] + [str(x) for x in range(7,11)]

# %% ../nbs/00_card.ipynb 10
from fastcore.basics import *
from fastcore.utils import *

# %% ../nbs/00_card.ipynb 11
class Card:
    'A playing card'
    def __init__(self, suit:int, rank:int, trump:int=11): store_attr()
    def __str__(self): return f'{ranks[self.rank]}{suits[self.suit]}' 
    __repr__ = __str__    

# %% ../nbs/00_card.ipynb 15
@patch
def __eq__(self:Card, a:Card): return (self.suit, self.rank)==(a.suit,a.rank)

# %% ../nbs/00_card.ipynb 19
@patch
def __lt__(self:Card, a:Card):
    return self.rank < a.rank if self.suit == a.suit else self.trump < a.rank

# %% ../nbs/00_card.ipynb 20
@patch
def __gt__(self:Card, a:Card):
    return self.rank > a.rank if self.suit == a.suit else self.trump > a.rank
