"""A deck of playing cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_deck.ipynb.

# %% auto 0
__all__ = ['Deck']

# %% ../nbs/01_deck.ipynb 3
from .card import *
from fastcore.test import *
from fastcore.utils import *

# %% ../nbs/01_deck.ipynb 4
class Deck:
    'A deck of 32 `Card`s, not including jokers and the number from 2 to 9'
    def __init__(self): self.cards = [Card(s,r) for s in range(len(suits)) for r in range(1,len(ranks))]
    def __len__(self): return len(self.cards)
    def __str__(self): return '; '.join(map(str,self.cards))
    def __contains__(self, card): return card in self.cards
    __repr__ = __str__

# %% ../nbs/01_deck.ipynb 11
@patch
def pop(self:Deck, idx=-1):
    'Remove and return one card from the deck'
    return self.cards.pop(idx)

# %% ../nbs/01_deck.ipynb 18
@patch
def remove(self:Deck, card:Card):
    'Removes `card` from the deck or raises exception if it is not there.'
    self.cards.remove(card)
